# Generated by Django 2.1.1 on 2018-09-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.IntegerField()),
                ('company', models.CharField(max_length=100, verbose_name='公司名')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('name', models.CharField(max_length=100, verbose_name='产品名')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='关键字')),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsClass')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='classes',
            field=models.ManyToManyField(blank=True, to='goods.GoodsClass'),
        ),
    ]
